# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a84c51eb7e0aef3af153c8aeb166180a1de06315a4fb355d7a0a7d103c61741fd07351b2aa583e310c38c42abbdac426cf2df5ad3f8101f7c2d635b05b2340b

test:
  secret_key_base: bd34788025428fc5f6413a6e976c1a7744b46c9c70e0e3030b7ee449c83dd6295fc49f1fd278b5ef55286455fda506017b4fc3f54da476c2864ec10771956f9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
